### PR TITLE
Add Video Search API

### PR DESCRIPTION
**Pull request by brunjo**
and some other small changes

### CODE REVIEW

**Comment by nadavshatz** [comment]
Hey @brunjo thanks for the PR!

Can I ask why did you remove the `semver` versioning?

**Comment by nadavshatz** [comment]
accidentally closed so reopened :)

**Comment by brunjo** [comment]
I got an error when I tried to add your gem to the Gemfile and run `bundle install` because the semver gem wasn't installed on my server. So I had to manually install the semver gem before I was able to install your gem. I think this is not very good.
The easiest way to fix it was to hardcode the version number into the gemspec file and remove the dependency.

**Comment by nadavshatz** [comment]
This is surprising considering its a dev dependency but I'm ok with it for now as this is not updated too often.

Looks good, I'll merge and push a new version into _rubygems_.

Maybe I'll generalize the search method even more at some point considering it's basically the same code between images and videos. but that's for another day.

Thanks Again!

**Pull request merged**
