### PR TITLE
Various enhancements

### PR DESCRIPTION
**Pull request by jkburges**
The intermediate fork (https://github.com/pexels/shutterstock-ruby) is no longer being maintained.

### CODE REVIEW

**Comment by nadavshatz** [comment]
Thanks for your commit! I'll get CI working and if it's all passing, I'll release a new version with the changes.

**Comment by nadavshatz** [comment]
I updated the Repo with a bunch of cleanup and fixed CI.
Please fix conflicts and then I can merge this once CI passes.

Thank you and sorry for the trouble

**Comment by tojofo** [comment]
> Thank you and sorry for the trouble

Don't apologise, we're stoked that PRs are being accepted, FWIW we love the gem, simple and does the job well for us, thanks for creating it.  (FYI I'm on the same team as @jkburges and @wbowling)

**Comment by jkburges** [comment]
Closing in favour of https://github.com/TailorBrands/shutterstock-ruby/pull/5 (that PR has conflicts fixed).

**Pull request closed without merging**
