### PR TITLE
Fix Special Characters Issue

### PR DESCRIPTION
**Pull request by brunjo**
The `URI.encode_www_form_component` method is not necessary. For example, if you search for "München", the API returned no results. Removing the encode method fixes this issue.

### CODE REVIEW

**Comment by nadavshatz** [comment]
Hey @brunjo ! Thanks a bunch for opening a PR. We've seen some issues in the past with not encoding request, but I'm okay with releasing a version with this and seeing if we get issues popping up.

Another thing - we are not using this library anymore so if you'd like to take over it let me know.

In any case - can you make sure the build passes before I merge this?

Thanks!

**Comment by brunjo** [comment]
Hey @nadavshatz!
The build now passes. We use this new version without the encoding in production and we haven't seen any issues.
I would like to take over the library if you don't want to maintain it anymore.

**Comment by nadavshatz** [comment]
@brunjo Merging now - looks good.
If we see that the maintenance gets lacking or takes too long I'll move it to you.

Thanks again for the PR!

**Comment by nadavshatz** [comment]
@brunjo new version has been release FYI https://rubygems.org/gems/shutterstock-ruby/versions/0.2.0

**Comment by brunjo** [comment]
Ok, great! Thanks for your fast response.

**Pull request merged**
