### PR TITLE
Allow purchase metadata and download existing purchase

### PR DESCRIPTION
**Pull request by wbowling**
- Allows you to check if a video has already been purchased and to get the download url for it
- Allows you to send through metadata when purchasing a video

### CODE REVIEW

**Comment by nadavshatz** [comment]
@wbowling thank you for your PR!

Would you be willing to add tests around your code? at least for the new methods you added?

**Comment by wbowling** [comment]
Sure thing, I'll add some tests and update the readme with the new methods

**Comment by nadavshatz** [comment]
Thanks!

**Comment by nadavshatz** [comment]
@wbowling thanks for all the work - looks great.
I'll merge and bump the minor version (0.5.0) cause you added a bunch of new features. 

then publish a release, I'll also update here when done.

Cheers 🍻

**Comment by nadavshatz** [comment]
@wbowling 0.5.0 is live. enjoy !

**Pull request merged**
